In this Use-Cases,the main aim to understand the cleaning and preprocessing of the text data in Natural Language processing

In [395]:
import pandas as pd
import nltk
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer
import string

In [396]:
df=pd.read_csv('amazon_co-ecommerce_sample.csv')
df.head()

,uniq_id,product_name,manufacturer,price,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,product_information,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,sellers
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,£3.42,5 new,15,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Product Description Hornby 2014 Catalogue Box ...,Technical Details Item Weight640 g Product Dim...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,Worth Buying For The Pictures Alone (As Ever) ...,"{""seller""=>[{""Seller_name_1""=>""Amazon.co.uk"", ..."
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,£16.99,NaN,2,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,Size Name:Large FunkyBuys® Large Christmas Hol...,Technical Details Manufacturer recommended age...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,Four Stars // 4.0 // 18 Dec. 2015 // By\n \...,"{""seller""=>{""Seller_name_1""=>""UHD WHOLESALE"", ..."
2,348f344247b0c1a935b1223072ef9d8a,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,£9.99,2 new,17,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Classic-Train-Lights-B...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,Technical Details Manufacturer recommended age...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...,**Highly Recommended!** // 5.0 // 26 May 2015 ...,"{""seller""=>[{""Seller_name_1""=>""DEAL-BOX"", ""Sel..."
3,e12b92dbb8eaee78b22965d2a9bbbd9f,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,£39.99,NaN,1,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,NaN,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,Technical Details Item Weight259 g Product Dim...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,NaN,NaN,I love it // 5.0 // 22 July 2013 // By\n \n...,NaN
4,e33a9adeed5f36840ccc227db4682a36,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,£32.19,NaN,3,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R6367-RailRoad-...,Product Description Hornby RailRoad 0-4-0 Gild...,Technical Details Item Weight159 g Product Dim...,Product Description Hornby RailRoad 0-4-0 Gild...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN,Birthday present // 5.0 // 14 April 2014 // By...,NaN

In [397]:
df.shape

(10000, 17)

In [398]:
df.isnull().sum()

uniq_id                                           0
product_name                                      0
manufacturer                                      7
price                                          1435
number_available_in_stock                      2500
number_of_reviews                                18
number_of_answered_questions                    765
average_review_rating                            18
amazon_category_and_sub_category                690
customers_who_bought_this_item_also_bought     1062
description                                     651
product_information                              58
product_description                             651
items_customers_buy_after_viewing_this_item    3065
customer_questions_and_answers                 9086
customer_reviews                                 21
sellers                                        3082
dtype: int64

In [399]:
df.columns

Index(['uniq_id', 'product_name', 'manufacturer', 'price',
       'number_available_in_stock', 'number_of_reviews',
       'number_of_answered_questions', 'average_review_rating',
       'amazon_category_and_sub_category',
       'customers_who_bought_this_item_also_bought', 'description',
       'product_information', 'product_description',
       'items_customers_buy_after_viewing_this_item',
       'customer_questions_and_answers', 'customer_reviews', 'sellers'],
      dtype='object')

In [400]:
df1=df.copy()

In [401]:
df1.shape

(10000, 17)

In [402]:
df1['price']

0        £3.42
1       £16.99
2        £9.99
3       £39.99
4       £32.19
         ...
9995    £22.95
9996    £39.99
9997    £43.99
9998    £49.81
9999    £21.20
Name: price, Length: 10000, dtype: object

In [403]:
df1['price_commas']=df1['price'][0][1:]
df1['price_commas']

0       3.42
1       3.42
2       3.42
3       3.42
4       3.42
        ...
9995    3.42
9996    3.42
9997    3.42
9998    3.42
9999    3.42
Name: price_commas, Length: 10000, dtype: object

In [404]:
df1['price_commas']=df1['price_commas'].astype('float')

In [405]:
df1.drop(['price'],axis=1,inplace=True)

In [406]:
df1.dtypes

uniq_id                                         object
product_name                                    object
manufacturer                                    object
number_available_in_stock                       object
number_of_reviews                               object
number_of_answered_questions                   float64
average_review_rating                           object
amazon_category_and_sub_category                object
customers_who_bought_this_item_also_bought      object
description                                     object
product_information                             object
product_description                             object
items_customers_buy_after_viewing_this_item     object
customer_questions_and_answers                  object
customer_reviews                                object
sellers                                         object
price_commas                                   float64
dtype: object

In [407]:
df1['number_of_reviews']=df1['number_of_reviews'].str.replace(',', '')

In [408]:
df1['number_of_reviews']=df1['number_of_reviews'].astype('float')

In [409]:
# seperate review column by //break
reviews=df1['customer_reviews'].str.split("//",n=4,expand=True)

In [410]:
df1['review_title']=reviews[0]
df1['rating']=reviews[1]
df1['review_date']=reviews[2]
df1['customer_name']=reviews[3]
df1['review']=reviews[4]

In [411]:
df1.head()

,uniq_id,product_name,manufacturer,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,...,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,customer_reviews,sellers,price_commas,review_title,rating,review_date,customer_name,review
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Product Description Hornby 2014 Catalogue Box ...,...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,Worth Buying For The Pictures Alone (As Ever) ...,"{""seller""=>[{""Seller_name_1""=>""Amazon.co.uk"", ...",3.42,Worth Buying For The Pictures Alone (As Ever),4.0,6 April 2014,By\n \n Copnovelist\n \n on 6 April 2014,Part of the magic for me growing up as a boy ...
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,Size Name:Large FunkyBuys® Large Christmas Hol...,...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,Four Stars // 4.0 // 18 Dec. 2015 // By\n \...,"{""seller""=>{""Seller_name_1""=>""UHD WHOLESALE"", ...",3.42,Four Stars,4.0,18 Dec. 2015,By\n \n kenneth bell\n \n on 18 Dec. 2...,Very happy with the communication with funkyb...
2,348f344247b0c1a935b1223072ef9d8a,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,2 new,17.0,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Classic-Train-Lights-B...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...,**Highly Recommended!** // 5.0 // 26 May 2015 ...,"{""seller""=>[{""Seller_name_1""=>""DEAL-BOX"", ""Sel...",3.42,**Highly Recommended!**,5.0,26 May 2015,By\n \n Simon.B :-)\n \n on 26 May 2015,Simple & GREAT FUN for 5+My nephews face was ...
3,e12b92dbb8eaee78b22965d2a9bbbd9f,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,NaN,1.0,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,NaN,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,...,NaN,NaN,I love it // 5.0 // 22 July 2013 // By\n \n...,NaN,3.42,I love it,5.0,22 July 2013,By\n \n Lilla Lukacs\n \n on 22 July 2...,I love it. Perfect with the earlier ordered l...
4,e33a9adeed5f36840ccc227db4682a36,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,NaN,3.0,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R6367-RailRoad-...,Product Description Hornby RailRoad 0-4-0 Gild...,...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN,Birthday present // 5.0 // 14 April 2014 // By...,NaN,3.42,Birthday present,5.0,14 April 2014,By\n \n Love my Dog\n \n on 14 April 2...,Bought this for my Grandson's birthday. He i...

In [412]:
df1.drop(['customer_reviews'],axis=1,inplace=True)

In [413]:
split_function=df1['customer_name'].str.split('\n',n=4,expand=True)
split_function

        0     1                    2   3                   4
0      By                Copnovelist        on 6 April 2014
1      By               kenneth bell        on 18 Dec. 2015
2      By                Simon.B :-)         on 26 May 2015
3      By               Lilla Lukacs        on 22 July 2013
4      By                Love my Dog       on 14 April 2014
...   ...   ...                  ...  ..                 ...
9995   By                        Ray        on 31 Mar. 2014
9996   By                   Janet R.         on 9 Dec. 2014
9997   By            Amazon Customer        on 18 Dec. 2015
9998   By                  Sodam Yat         on 13 May 2010
9999   By              graham mccoid        on 31 Aug. 2015

[10000 rows x 5 columns]

In [414]:
df1['customer_name']=split_function[2]

In [415]:
df1['customer_name'].head(10)

0             Copnovelist
1            kenneth bell
2             Simon.B :-)
3            Lilla Lukacs
4             Love my Dog
5        catherine baines
6             Steve Guess
7              Adam Irwin
8           Mr. K. Waller
9                J. Negus
Name: customer_name, dtype: object

In [416]:
#Defining A Function to Remove punctuation
import string
def remove_punctuation(text):
    no_punct = "".join([c for c in text if c not in string.punctuation])
    return no_punct

In [417]:
split_function=df1['review'].str.split('//',n=4,expand=True)
split_function[0]

0        Part of the magic for me growing up as a boy ...
1        Very happy with the communication with funkyb...
2        Simple & GREAT FUN for 5+My nephews face was ...
3        I love it. Perfect with the earlier ordered l...
4        Bought this for my Grandson's birthday.  He i...
                              ...
9995     Very true to the Batman classic series of the...
9996     Its a Christmas present however from what I s...
9997                       arrived in excellent condition
9998     Okay, Hal Jordan figures come and go. There i...
9999     1st class kit top marks to bandai if your not...
Name: 0, Length: 10000, dtype: object

In [418]:
df2=split_function[0]

In [419]:
df1.head()

,uniq_id,product_name,manufacturer,number_available_in_stock,number_of_reviews,number_of_answered_questions,average_review_rating,amazon_category_and_sub_category,customers_who_bought_this_item_also_bought,description,...,product_description,items_customers_buy_after_viewing_this_item,customer_questions_and_answers,sellers,price_commas,review_title,rating,review_date,customer_name,review
0,eac7efa5dbd3d667f26eb3d3ab504464,Hornby 2014 Catalogue,Hornby,5 new,15.0,1.0,4.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Product Description Hornby 2014 Catalogue Box ...,...,Product Description Hornby 2014 Catalogue Box ...,http://www.amazon.co.uk/Hornby-R8150-Catalogue...,Does this catalogue detail all the previous Ho...,"{""seller""=>[{""Seller_name_1""=>""Amazon.co.uk"", ...",3.42,Worth Buying For The Pictures Alone (As Ever),4.0,6 April 2014,Copnovelist,Part of the magic for me growing up as a boy ...
1,b17540ef7e86e461d37f3ae58b7b72ac,FunkyBuys® Large Christmas Holiday Express Fes...,FunkyBuys,NaN,2.0,1.0,4.5 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,Size Name:Large FunkyBuys® Large Christmas Hol...,...,Size Name:Large FunkyBuys® Large Christmas Hol...,http://www.amazon.co.uk/Christmas-Holiday-Expr...,can you turn off sounds // hi no you cant turn...,"{""seller""=>{""Seller_name_1""=>""UHD WHOLESALE"", ...",3.42,Four Stars,4.0,18 Dec. 2015,kenneth bell,Very happy with the communication with funkyb...
2,348f344247b0c1a935b1223072ef9d8a,CLASSIC TOY TRAIN SET TRACK CARRIAGES LIGHT EN...,ccf,2 new,17.0,2.0,3.9 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Classic-Train-Lights-B...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,...,BIG CLASSIC TOY TRAIN SET TRACK CARRIAGE LIGHT...,http://www.amazon.co.uk/Train-With-Tracks-Batt...,What is the gauge of the track // Hi Paul.Trut...,"{""seller""=>[{""Seller_name_1""=>""DEAL-BOX"", ""Sel...",3.42,**Highly Recommended!**,5.0,26 May 2015,Simon.B :-),Simple & GREAT FUN for 5+My nephews face was ...
3,e12b92dbb8eaee78b22965d2a9bbbd9f,HORNBY Coach R4410A BR Hawksworth Corridor 3rd,Hornby,NaN,1.0,2.0,5.0 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,NaN,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,...,Hornby 00 Gauge BR Hawksworth 3rd Class W 2107...,NaN,NaN,NaN,3.42,I love it,5.0,22 July 2013,Lilla Lukacs,I love it. Perfect with the earlier ordered l...
4,e33a9adeed5f36840ccc227db4682a36,Hornby 00 Gauge 0-4-0 Gildenlow Salt Co. Steam...,Hornby,NaN,3.0,2.0,4.7 out of 5 stars,Hobbies > Model Trains & Railway Sets > Rail V...,http://www.amazon.co.uk/Hornby-R6367-RailRoad-...,Product Description Hornby RailRoad 0-4-0 Gild...,...,Product Description Hornby RailRoad 0-4-0 Gild...,http://www.amazon.co.uk/Hornby-R2672-RailRoad-...,NaN,NaN,3.42,Birthday present,5.0,14 April 2014,Love my Dog,Bought this for my Grandson's birthday. He i...

In [420]:
df1['review']

0        Part of the magic for me growing up as a boy ...
1        Very happy with the communication with funkyb...
2        Simple & GREAT FUN for 5+My nephews face was ...
3        I love it. Perfect with the earlier ordered l...
4        Bought this for my Grandson's birthday.  He i...
                              ...
9995     Very true to the Batman classic series of the...
9996     Its a Christmas present however from what I s...
9997                       arrived in excellent condition
9998     Okay, Hal Jordan figures come and go. There i...
9999     1st class kit top marks to bandai if your not...
Name: review, Length: 10000, dtype: object

In [421]:
df1['review']=split_function[0]
df1['review']

0        Part of the magic for me growing up as a boy ...
1        Very happy with the communication with funkyb...
2        Simple & GREAT FUN for 5+My nephews face was ...
3        I love it. Perfect with the earlier ordered l...
4        Bought this for my Grandson's birthday.  He i...
                              ...
9995     Very true to the Batman classic series of the...
9996     Its a Christmas present however from what I s...
9997                       arrived in excellent condition
9998     Okay, Hal Jordan figures come and go. There i...
9999     1st class kit top marks to bandai if your not...
Name: review, Length: 10000, dtype: object

In [422]:
df1['review'].dtypes

dtype('O')

In [423]:
# Removing Punctuation marks using Regular Expressions
tokenizer=RegexpTokenizer(r"\w+")

In [424]:
# Doubt in making it lower
#df1['review']=df1['review'].apply(lambda x:tokenizer.tokenize(x.lower()))

In [425]:
df1['review'][0]

" Part of the magic for me growing up as a boy was to buy (or be given) the new Hornby catalogue every year, even if it included 90% of the same products as the previous year.  I've still got my old ones dating back to the 70s and 80s somewhere.  These days the catalogue is especially informative in that it tells you the vintage of the rolling stock which is useful if you are dedicating your railway to one particular era and train company. | Amazing detail fabulous photography. "

In [426]:
# removing stopword
def remove_stopwords(text):
    words=[w for w in text if w not in stopwords.words('english')]
    return words

In [427]:
#Doubt
#df1['review']=df1['review'].apply(lambda x: remove_stopwords(x))

In [428]:
# Handling Missing Values in NLP
df1.isnull().sum()

uniq_id                                           0
product_name                                      0
manufacturer                                      7
number_available_in_stock                      2500
number_of_reviews                                18
number_of_answered_questions                    765
average_review_rating                            18
amazon_category_and_sub_category                690
customers_who_bought_this_item_also_bought     1062
description                                     651
product_information                              58
product_description                             651
items_customers_buy_after_viewing_this_item    3065
customer_questions_and_answers                 9086
sellers                                        3082
price_commas                                      0
review_title                                     21
rating                                           21
review_date                                      21
customer_name                                   173
review                                           21
dtype: int64

In [429]:
df1['manufacturer'].dropna(inplace=True)

In [430]:
df1.drop(['uniq_id'],axis=1,inplace=True)

In [431]:
df1.shape

(10000, 20)

In [440]:
percent= 100*(len(df1.loc[:,df1.isnull().sum(axis=0)>=1 ].index) / len(df1.index))
print(round(percent,2))

100.0

In [442]:
percent_missing = df1.isnull().sum() * 100 / len(df)
missing_value_df = pd.DataFrame({'column_name': df1.columns,
                                 'percent_missing': percent_missing})
missing_value_df

,column_name,percent_missing
product_name,product_name,0.00
manufacturer,manufacturer,0.07
number_available_in_stock,number_available_in_stock,25.00
number_of_reviews,number_of_reviews,0.18
number_of_answered_questions,number_of_answered_questions,7.65
average_review_rating,average_review_rating,0.18
amazon_category_and_sub_category,amazon_category_and_sub_category,6.90
customers_who_bought_this_item_also_bought,customers_who_bought_this_item_also_bought,10.62
description,description,6.51
product_information,product_information,0.58
product_description,product_description,6.51
items_customers_buy_after_viewing_this_item,items_customers_buy_after_viewing_this_item,30.65
customer_questions_and_answers,customer_questions_and_answers,90.86
sellers,sellers,30.82
price_commas,price_commas,0.00
review_title,review_title,0.21
rating,rating,0.21
review_date,review_date,0.21
customer_name,customer_name,1.73
review,review,0.21

In [443]:
missing_value_df.sort_values('percent_missing', inplace=True)
missing_value_df

,column_name,percent_missing
product_name,product_name,0.00
price_commas,price_commas,0.00
manufacturer,manufacturer,0.07
number_of_reviews,number_of_reviews,0.18
average_review_rating,average_review_rating,0.18
review_date,review_date,0.21
rating,rating,0.21
review_title,review_title,0.21
review,review,0.21
product_information,product_information,0.58
customer_name,customer_name,1.73
product_description,product_description,6.51
description,description,6.51
amazon_category_and_sub_category,amazon_category_and_sub_category,6.90
number_of_answered_questions,number_of_answered_questions,7.65
customers_who_bought_this_item_also_bought,customers_who_bought_this_item_also_bought,10.62
number_available_in_stock,number_available_in_stock,25.00
items_customers_buy_after_viewing_this_item,items_customers_buy_after_viewing_this_item,30.65
sellers,sellers,30.82
customer_questions_and_answers,customer_questions_and_answers,90.86

In [474]:
df1['sellers']

0       {"seller"=>[{"Seller_name_1"=>"Amazon.co.uk", ...
1       {"seller"=>{"Seller_name_1"=>"UHD WHOLESALE", ...
2       {"seller"=>[{"Seller_name_1"=>"DEAL-BOX", "Sel...
3                                                     NaN
4                                                     NaN
                              ...
9995    {"seller"=>[{"Seller_name_1"=>"Star Action Fig...
9996                                                  NaN
9997    {"seller"=>[{"Seller_name_1"=>"YUK", "Seller_p...
9998    {"seller"=>[{"Seller_name_1"=>"Smaller World F...
9999                                                  NaN
Name: sellers, Length: 10000, dtype: object